seed: [11, 22, 33]
run_name: no_aug
model_name: "resnet50"

training:
  num_epochs: 200
  patience_for_scheduler: 10
  lr: 1e-4
  metric_to_monitor: "Val/Accuracy"
  use_training_augmentations: False
